# taints means it is paints (pollute) , kube-scheduler responsibility it schedule pods on to workernodes ..
# taint and schedulers are to repel(reject) the nodes , we can  mark the node as tainted so that scheduler will not schedule any pods on to it
# if you apply tolerate scheduler can schedule the  pods  on tainted nodes 

apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx  #nginx:stable-perl 
  nodeSelector:
    hardware: gpu
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect:  "NoSchedule"
    
