# to attract to your nodes , schedule the labels , some changes labels in run time ignore them..
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      # hard ware
      requiredDuringSchedulingIgnoredDuringExecution:  # labels match 
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            values:
            - gpu
  containers:
  # docker run -d --name nginx nginx
  - name: nginx
    image: nginx:stable-perl
  # nodeSelector:
  #   hardware: gpu
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
    